# Assumes brew bundle has finished and installed all of the software

- hosts: localhost
  roles:
    # Fonts
    - { role: font, tags: "font" }

    # Programming languages
    - { role: node, tags: "node" }
    - { role: golang, tags: "golang" }
    - { role: rust, tags: "rust" }
    - { role: elixir, tags: "elixir" }
    - { role: python, tags: "python" }
    - { role: cpp, tags: "cpp" }

    # Shell
    - { role: zsh, tags: "zsh" }

    # Editors
    - { role: nvim, tags: "neovim" }
    - { role: vscode, tags: "vscode" }
