---

- name: Ensure .config directory exists
  file:
    path: "{{ user.home }}/.config"
    state: directory

- name: Symlink nvim config
  file:
    src: "{{ playbook_dir }}/../dotfiles/nvim"
    dest: "{{ user.home }}/.config/nvim"
    state: link
    force: yes
